### PR TITLE
Update `airtable` to latest version, v0.7.2

### PR DESCRIPTION
**Pull request by EvanHahn**
This updates `airtable` to the latest version, v0.7.2. [See the changelog][1] for more info on what changed, but I expect no breakages.

[1]: https://github.com/Airtable/airtable.js/blob/v0.7.2/CHANGELOG.md

### CODE REVIEW

**Comment by zharikovpro** [comment]
@EvanHahn  It looks sane and I want to merge this. However, I stopped using AirTable a while ago and cannot check it myself. Have you tried backup using this upgraded lib version?

**Comment by EvanHahn** [comment]
I haven't, and there don't appear to be any tests in this repo. What's the best way to verify that things still work?

**Comment by zharikovpro** [comment]
> I haven't, and there don't appear to be any tests in this repo.

Yes, it was a one-time script :)

> What's the best way to verify that things still work?

Backup AirTable database with several tables and with some attachments.

**Comment by EvanHahn** [comment]
I got a "NotLoggedIn" error when trying to use the version from npm.

On a completely fresh Ubuntu 16.04.6 machine:

```sh
sudo snap install node --classic --channel=12

sudo npm install -g airtable-backup

airtable-backup 'my.email@example.com' 'my_password'
# Error: NotLoggedIn
#    at bases (/usr/local/lib/node_modules/airtable-backup/lib.js:25:11)
#    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

I want to make sure to fix this before trying out this branch. Any guidance?

**Comment by zharikovpro** [comment]
Okay, I can reproduce it. This error points to this line: https://github.com/zharikovpro/airtable-backup/blob/master/lib.js#L24

And that means that AirTable has changed their site and this tool doesn't work anymore :( This check probably can be fixed but requires an investigation. I see that now this request returns status 302 (redirect) and this should be treated as a successful login.

Something like:

```
if (session.status !== 302) {
  throw new Error('NotLoggedIn')
}
```

**Comment by zharikovpro** [comment]
I've tried this quickly, and unfortunately, the status code check fails. AirTable must have changed something on their site and this script fails to log in properly.

As I don't use this script anymore, it's hard for me to find a time to fix this. If you are willing to invest in it, I'll happily check out the fix and merge it.

**Comment by EvanHahn** [comment]
Airtable.js versions prior to 0.7.2 have [a security vulnerability](https://www.npmjs.com/advisories/1305). Given that the script doesn't work anyway, how would you feel about doing the version bump (probably by merging this PR)?

**Comment by zharikovpro** [comment]
Okay, happy with it

**Comment by EvanHahn** [comment]
Great, thanks!

**Pull request merged**
